### ISSUE TITLE
As an asker, I want to attach a bounty (in ETH) to my question, so that I can create an incentive for people to answer my question.

### ISSUE THREAD

**Issue by chris-chao** [nyu-software-engineering/ethereum-marketplacer#18]

**Comment by NikitaM97** [comment]
Acceptance Criteria: 

- [] When a user can post a question to the platform with a clearly visible bounty attached to the question.

**Comment by AlvaroLuken** [comment]
- [ ] Asker is able to post a question and stake ETH with it
- [ ] Smart contract holds ETH while transaction is still open (asker has not accepted an answer)
- [ ] Solvers can see bounty once question is posted
