### ISSUE TITLE
As an asker, I want to submit a question, so that it is displayed on the platform and it creates a smart contract containing my bounty and time-constraint.

### ISSUE THREAD

**Issue by chris-chao** [nyu-software-engineering/ethereum-marketplacer#20]

**Comment by NikitaM97** [comment]
Acceptance Criteria

- [ ] When an asker can post a question to the platform, and automatically create a smart contract on the blockchain platform which contains their bounty and time constraint.

**Comment by AlvaroLuken** [comment]
- [ ] Asker is able to post a question
- [ ] Smart contract is created once a question is posted
- [ ] Smart contract interacts with asker and solver(s) addresses
- [ ] Smart contract holds staked ETH
- [ ] Asker is able to attach time constraint
- [ ] Smart contract expires once time is up
