### ISSUE TITLE
As a browser, I want to look at a list of submitted questions, so that I can (eventually) choose a question I would like to answer.

### ISSUE THREAD

**Issue by chris-chao** [nyu-software-engineering/ethereum-marketplacer#21]

**Comment by NikitaM97** [comment]
Acceptance Criteria: 

- [ ] As a browser, I would like to see questions on the platforms, see their bounties, see their time constraints, and see which questions I would like to answer.

**Comment by AlvaroLuken** [comment]
- [ ] Jump from Google to front end works
- [ ] User with MetaMask plugin can post a question
- [ ] User with MetaMask plugin can select a question to solve
- [ ] User can submit an answer to be considered for bounty prize
