### ISSUE TITLE
Write core functionality for Smart Contract

### ISSUE THREAD

**Issue by chris-chao** [nyu-software-engineering/ethereum-marketplacer#24]
- Smart Contract created by submit_question.onClick()
- Allow user to send specified amount to contract address
- Allow user to declare a time_constraint
- Send all funds back to user's address after time_constraint has been reached

**Comment by AlvaroLuken** [comment]
@chris-chao can you decide whether this still remains an issue?

**Comment by AlvaroLuken** [comment]
This is not an issue.
