### ISSUE TITLE
Decide technology stack for whole project:

### ISSUE THREAD

**Issue by chris-chao** [nyu-software-engineering/ethereum-marketplacer#27]
- Front-end: HTML/CSS/Javascript/bootstrap?
- Back-end: Node.js
- Smart Contract: Solidity in a Truffle Framework
- Databasing: MongoDB

**Comment by AlvaroLuken** [comment]
I vote to close this issue. Can someone please confirm and if so, close this issue.

**Comment by AlvaroLuken** [comment]
We have decided... 
React for front end
Solidity for smart contract
Javascript
