### ISSUE TITLE
As an asker, I want to be able to accept an answer, so that the bounty will be released to the answerer.

### ISSUE THREAD

**Issue by chris-chao** [nyu-software-engineering/ethereum-marketplacer#35]

**Comment by AlvaroLuken** [comment]
ACCEPTANCE CRITERIA

- [] Asker is given submitted answers for review - in a scrollable list
- [] Asker is able to accept ONE submitted answer
- [] Asker is able to see full answer (without blur), once accepted 
- [] Bounty is credited to the solver's address
- [] Bounty is no longer in either asker address or smart contract
